import Header from "@/components/organisms/Header";
import Providers from "@/hooks/Providers";
import { languages } from "@/lib/i18n/settings";
import { cn } from "@/lib/utils";
import { PageWithChildrenProps } from "@/types/common";
import { dir } from 'i18next';
import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "../globals.css";

const inter = Inter({ subsets: ["latin"] });

export async function generateStaticParams() {
  return languages.map((lng) => ({ lng }))
}

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children, params: { lng } }: PageWithChildrenProps) {
  return (
    <html lang={lng} dir={dir(lng)}>
      <head>
      </head>
      <body className={cn(inter.className, 'flex flex-col w-screen h-svh bg-primary-foreground')}>
        <Providers language={lng}>
          <Header />
          <main className="grow w-full max-w-5xl mx-auto">
            {children}
          </main>
        </Providers>
      </body>
    </html>
  );
}
