import { ThemeProvider } from "@/components/ThemeProvider";
import { Language, languages } from "@/lib/i18n/settings";
import { dir } from 'i18next';
import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "../globals.css";

const inter = Inter({ subsets: ["latin"] });

export async function generateStaticParams() {
  return languages.map((lng) => ({ lng }))
}

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

interface RootLayoutProps {
  children: React.ReactNode;
  params: { lng: Language }
}

export default function RootLayout({ children, params: { lng } }: Readonly<RootLayoutProps>) {
  return (
    <html lang={lng} dir={dir(lng)}>
      <head>
      </head>
      <body className={inter.className}>
        <ThemeProvider
          attribute="class"
          defaultTheme="system"
          enableSystem
          disableTransitionOnChange
        >
          {children}
        </ThemeProvider>
      </body>
    </html>
  );
}
